site_name: Red Bulldog HW3
site_url: https://exectly7.github.io/hw3-groudyna/ 
repo_url: https://github.com/exectly7/hw3-groudyna

docs_dir: files/

nav:
  - Главная: index.md
  - Документация:
      - Процесс: docs/contribution.md
      - Работа команды: docs/workflow.md
      - CI/CD: docs/ci-cd.md
  - Содержание: 
      - Анкета: content/questionnaire.md
      - Заполненная анкета: content/questionnaire.md
      - Повестка рабочей встречи: content/interview-questions.md
      - Протокол рабочей встречи: content/interview-protocol.md
      - План коммуникаций: content/interview-protocol.md
  - Финальные варианты документов:
      - Финальная анкета: final/questionnaire-final.md
      - Финальная повестка рабочей встречи: final/interview-final.md
      - Финальный план коммуникаций: final/communication-plan-final.md